# Auto-generated by theme-set
# Theme: {{name}} ({{type}})

export THEME_NAME="{{name}}"
export THEME_TYPE="{{type}}"
export THEME_BG="{{bg}}"
export THEME_BG2="{{bg2}}"
export THEME_FG="{{fg}}"
export THEME_ACCENT="{{accent}}"
export THEME_SEL="{{sel}}"
export THEME_MUTED="{{muted}}"
export THEME_RED="{{red}}"
export THEME_GREEN="{{green}}"
export THEME_YELLOW="{{yellow}}"
export THEME_BLUE="{{blue}}"
export THEME_PURPLE="{{purple}}"
export THEME_CYAN="{{cyan}}"
export THEME_TEAL="{{teal}}"
export THEME_ORANGE="{{orange}}"
