# Auto-generated by theme-set
# Theme: {{name}} ({{type}})

export THEME_NAME="{{name}}"
export THEME_TYPE="{{type}}"
export THEME_BG="{{bg}}"
export THEME_BG2="{{bg2}}"
export THEME_FG="{{fg}}"
export THEME_ACCENT="{{accent}}"
export THEME_SEL="{{sel}}"
export THEME_MUTED="{{muted}}"
export THEME_RED="{{red}}"
export THEME_GREEN="{{green}}"
export THEME_YELLOW="{{yellow}}"
export THEME_BLUE="{{blue}}"
export THEME_PURPLE="{{purple}}"
export THEME_CYAN="{{cyan}}"
export THEME_TEAL="{{teal}}"
export THEME_ORANGE="{{orange}}"

# Clean LS_COLORS avoiding glaring background fills on other-writable (ow) & sticky (tw/st) dirs
export LS_COLORS="di=01;34:ln=01;36:so=01;35:pi=33:ex=01;32:bd=33;01:cd=33;01:su=37;41:sg=30;43:ca=30;41:tw=01;34:ow=01;34:st=01;34:${LS_COLORS}"

