[global]
frame_color = "{{accent}}"

[urgency_low]
background = "{{black}}"
foreground = "{{base05}}"
frame_color = "{{one_bg2}}"

[urgency_normal]
background = "{{black}}"
foreground = "{{white}}"
frame_color = "{{accent}}"

[urgency_critical]
background = "{{black}}"
foreground = "{{red}}"
frame_color = "{{red}}"
