[global]
frame_color = "{{accent}}"
highlight = "{{accent}}"

[urgency_low]
background = "{{black}}"
foreground = "{{base05}}"
frame_color = "{{one_bg2}}"
highlight = "{{one_bg2}}"

[urgency_normal]
background = "{{black}}"
foreground = "{{white}}"
frame_color = "{{accent}}"
highlight = "{{accent}}"

[urgency_critical]
background = "{{black}}"
foreground = "{{red}}"
frame_color = "{{red}}"
highlight = "{{red}}"

[app_volume]
appname = "Volume"
highlight = "{{blue}}"
frame_color = "{{blue}}"

[app_brightness]
appname = "Brightness"
highlight = "{{yellow}}"
frame_color = "{{yellow}}"

[app_nightlight]
appname = "Night Light"
highlight = "{{orange}}"
frame_color = "{{orange}}"

[app_screenshot]
appname = "Screenshot"
highlight = "{{teal}}"
frame_color = "{{teal}}"
