client.focused          {{accent}} {{bg2}} {{fg}} {{accent}} {{accent}}
client.focused_inactive {{one_bg2}} {{black}} {{base05}} {{one_bg2}} {{one_bg2}}
client.unfocused        {{darker_black}} {{black}} {{grey_fg}} {{darker_black}} {{darker_black}}
client.urgent           {{red}} {{black}} {{red}} {{red}} {{red}}
