bar {
    id bar-0
    mode invisible
    position bottom
    status_command ~/.local/bin/swaybar-status
    font pango:Iosevka Nerd Font 11
    colors {
        background {{black}}
        statusline {{white}}
        separator {{grey}}
        focused_workspace {{accent}} {{one_bg}} {{accent}}
        active_workspace {{blue}} {{one_bg}} {{white}}
        inactive_workspace {{one_bg}} {{black}} {{grey_fg}}
        urgent_workspace {{red}} {{red}} {{black}}
    }
}
