client.focused          {{accent}} {{black}} {{white}} {{green}} {{accent}}
client.focused_inactive {{one_bg}} {{black}} {{base05}} {{one_bg2}} {{one_bg}}
client.unfocused        {{darker_black}} {{black}} {{grey_fg}} {{darker_black}} {{darker_black}}
client.urgent           {{red}} {{red}} {{black}} {{red}} {{red}}
