general.import = ["/home/manisk/.local/state/theme/alacritty.toml"]

[font]
size = 21.5
# normal = { family = "Departure Mono", style = "Normal" }
# bold = { family = "Departure Mono", style = "Bold" }
# italic = { family = "Departure Mono", style = "Normal" }
# bold_italic = { family = "Departure Mono", style = "Bold" }

normal = { family = "VictorMono Nerd Font", style = "Bold" }
bold = { family = "VictorMono Nerd Font", style = "Bold" }
italic = { family = "VictorMono Nerd Font", style = "Bold" }
bold_italic = { family = "VictorMono Nerd Font", style = "Bold" }

[cursor]
style = { shape = "Block", blinking = "Off" }

[selection]
save_to_clipboard = true

[[hints.enabled]]
regex = "(https?|ftp|file|git|ssh|mailto)://[^\\s<>\"'()\\[\\]{}|^`]+"
hyperlinks = true
command = "xdg-open"
post_processing = true
mouse = { mods = "None", enabled = true }
binding = { key = "O", mods = "Control|Shift" }

[keyboard]
bindings = [
  { key = "U", mods = "Alt|Shift", action = "IncreaseFontSize" },
  { key = "Y", mods = "Alt|Shift", action = "DecreaseFontSize" }
]
