--ignore-gpu-blocklist
--enable-gpu-rasterization
--enable-zero-copy
--use-gl=angle
--use-angle=gl
--enable-features=VaapiVideoDecodeLinuxGL,VaapiVideoDecoder,CanvasOopRasterization,SmoothScrolling
--disable-features=VulkanVideoDecoder,Vulkan
--password-store=basic
--enable-blink-features=MiddleClickAutoscroll
--test-type
